Use stable stringify when creating payload segments
decentralized-identity/did-jwt pull request #161
Opened 2021-04-30 07:08 UTC by zbarbuto

When creating the segments of a JWT, regular `JSON.stringify()` was being used. Because the ordering is not guaranteed with JSON.stringify - this makes re-creating the JWT out of a W3C format credential very difficult.

By using [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) there can be a guaranteed ordering of the properties, meaning as long as the payload contains exactly the same content, you will always get the same JWT (see added test which fails without these changes)

I have also replaced ncal-did with regular jwt decode in the test - nacl-did is [marked as deprecated](https://github.com/uport-project/nacl-did) and was only used in this one place.

2021-04-30 10:00 UTC, mirceanis requested changes
Hi, thank you for the contribution!

It looks like you are looking for a way to canonicalize the payload before signing.
I think if you are working with already canonical JSON, then `JSON.stringify` will behave properly.
I'm not against performing this canonicalization, but I think that should be an opt-in, not a default. Existing users may not like their payloads to be modified.

That being said, the standard way of doing canonicalization of JSON in cryptographic situations is JCS, described by [RFC8785](https://tools.ietf.org/html/rfc8785) which also lists [canonicalize](https://github.com/erdtman/canonicalize) as a zero-dependency javascript implementation of JCS.

I would suggest using `canonicalize` instead of `json-stable-stringify` since the later also seems to have [serious issues](https://github.com/substack/json-stable-stringify/issues) and doesn't look like it's maintained.

Also, please make a separate PR for the removal of `nacl-did` from the `devDependencies` and from tests.

2021-05-17 14:51 UTC, mirceanis commented
@zbarbuto It seems that other projects are successfully using [fast-json-stable-stringify](https://github.com/epoberezkin/fast-json-stable-stringify) to stabilise the payload [before sending it to be signed](https://github.com/ceramicnetwork/key-did-provider-ed25519/blob/07ce5976c22a0798416ef2c1217c86f8e99720fb/src/index.ts#L19)

You might want to try that one and see if it resolves your issue.
If that works, please close this PR, otherwise please make the required changes.
Thank you for your contribution!

2021-05-17 22:54 UTC, zbarbuto commented
As requested I have replaced `json-stable-stringify` with `canonicalize` and made canonicalization optional with a new `canonicalize` option in `createJWT` / `createJWS`

2021-05-17 23:10 UTC, zbarbuto commented
CI failure does not appear related to my changes that I can see - the issue is in uploading coverage reports.

2021-05-18 15:45 UTC, mirceanis approved these changes
looks great, thanks for the contribution!

2021-05-18 15:47 UTC, merged