Added support for authenticated encryptioin
decentralized-identity/did-jwt pull request #177
Opened 2021-05-25 10:44 UTC by awoie

Added ECDH-1PU+XC20PKW, AuthEncrypter/Decrypter and AnonEncrypter/Decrypter

2021-05-25 10:45 UTC, awoie commented
@oed pls review again

2021-05-26 15:29 UTC, mirceanis approved these changes
looks good to me

2021-05-28 10:05 UTC, mirceanis requested changes
I added some suggestions for what could be slightly better names for some methods and a reminder to also export the new methods in `index.ts`

2021-05-28 10:05 UTC, mirceanis commented on src/xc20pEncryption.ts
> +export function AnonEncrypter(publicKey: Uint8Array,
```suggestion
export function createAnonEncrypter(publicKey: Uint8Array, 
```

2021-05-28 10:05 UTC, mirceanis commented on src/xc20pEncryption.ts
> +export function AuthDecrypter(recipientSecretKey: Uint8Array, senderPublicKey: Uint8Array): Decrypter {
```suggestion
export function createAuthDecrypter(recipientSecretKey: Uint8Array, senderPublicKey: Uint8Array): Decrypter {
```

2021-05-28 10:05 UTC, mirceanis commented on src/xc20pEncryption.ts
> +export function AnonDecrypter(secretKey: Uint8Array): Decrypter {
```suggestion
export function createAnonDecrypter(secretKey: Uint8Array): Decrypter {
```

2021-05-28 16:57 UTC, mirceanis approved these changes
looks good to me

2021-05-29 14:00 UTC, oed approved these changes
lgtm. Would be nice to have Some API documentation for the JWE stuff though!

2021-05-31 09:48 UTC, merged